### ISSUE TITLE
Malware detected from ESET Antivirus

### ISSUE THREAD

**Issue by mack0196** [wakatime/wakatime-cli#1031]
Malware scanning found a trojan in wakatime extension files and disabled the extension.

```
Real-time file system protection;file;C:\Users\XXX\.wakatime\wakatime-cli-windows-amd64.exe;a variant of WinGo/Agent_AGen.AN trojan;cleaned by deleting;

Event occurred during an attempt to run the file by the application: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.exe
```

Could a security audit be performed to verify and clean if found?

**Comment by alanhamlett** [comment]
This started happening after we [upgraded Go](https://github.com/wakatime/wakatime-cli/compare/v1.89.1...v1.90.0) in the wakatime-cli part of the extension. I used [this guide](https://github.com/yaronelh/False-Positive-Center) to report the false positive to Trend Micro.

**Comment by mack0196** [comment]
Thanks. I originally said trend micro but we are using eset. Have you filed similar report https://support.eset.com/en/kb141-submit-a-virus-website-or-potential-false-positive-sample-to-the-eset-lab?

**Comment by alanhamlett** [comment]
> Thanks. I originally said trend micro but we are using eset. Have you filed similar report https://support.eset.com/en/kb141-submit-a-virus-website-or-potential-false-positive-sample-to-the-eset-lab?

I also sent it to ESET and received this response:

```
Hello,

Thank you for your submission.
It was a false positive which was fixed yesterday.

Regards,

ESET Malware Response Team
```

**Comment by PaltryProgrammer** [comment]
![Infected](https://github.com/user-attachments/assets/b05e306a-0e30-4016-adfa-f8ea02454ac8)
![Avast Free Antivirus](https://github.com/user-attachments/assets/51291c1e-a771-4ba1-bd75-b5ba5445fe71)

**Comment by alanhamlett** [comment]
It's not showing up as blocked on any major av providers:
https://www.virustotal.com/gui/file/5f308842c8da2cb7c4de041df545327bb493d5d9d9779ceec1351e5a8082869d

As long as you haven't disabled SSL in your `~/.wakatime.cfg` then it's safe. Just click `More Options` and allow it.

**Comment by RecNes** [comment]
It's happening to me now. Windows "Defender" telling this and blocking files to run:

<img width="1000" height="682" alt="Image" src="https://github.com/user-attachments/assets/cfb7d114-0f8e-4693-8fc3-4c9fd7a3bc12" />

Why this is happening since 2022? What is the technical explanation of this incidents? Is this the problem of antivirus companies' incompetence?

**Comment by alanhamlett** [comment]
It's a false positive, yes it's a problem with antivirus incorrectly flagging it. The binary isn't labeled as malicious as far as we can tell:

https://www.virustotal.com/gui/url/b89d4f0cc328ab76760f1b98c1cb792a355064fe608c0b1a84553a2ef2005878?nocache=1

I've submitted the file to WIndows Defender so it should be unblocked soon.

**Comment by FelixIsaac** [comment]
+1 I'm also finding this false positive problem on Windows. Has Windows Defender Team replied since October? Thank you for the kind work you all do at Wakatime :)

<img width="547" height="713" alt="Image" src="https://github.com/user-attachments/assets/44c46f38-db2c-4330-86e9-9b70994ca362" />

EDIT: I just ran the file on [VirusTotal](https://www.virustotal.com/gui/file/73929453764549244a4d567f704c1db489999bdd46d14b1f324236df078189ad). Is this 19/64 normal considering that (presumably) the application has to know what app you're on.

<img width="1186" height="869" alt="Image" src="https://github.com/user-attachments/assets/2bedd274-f0f1-403e-9ce7-93068f7c1490" />
