### ISSUE TITLE
Concurrent pipelines shouldn't break semver

### ISSUE THREAD

**Issue by gandarez** [wakatime/wakatime-cli#406]
We might be aware that concurrent pipelines might break semver calculation. The explanation is simple. When a PR gets merged to either `master` or `develop` it runs (on_push.yml) 6 test jobs to aftwerwards run `Release` which is the step that the magic happens. We **MUST** merge a PR **only if no pipeline is running at develop or master**.

**Comment by alanhamlett** [comment]
We can run a `Pre-Release` step that claims a version with a tag, or by creating the Draft Release?

**Comment by dron22** [comment]
Claiming version is a good idea :+1: Also the tests should never fail, as we only allow PR merges with passing tests.

**Comment by gandarez** [comment]
I've been working around creating a draft release but it's somehow problematic. It doesn't return correctly when calling the API also it doesn't trigger any workflow when created. Anyways I'll find a proper way to do that.

**Comment by alanhamlett** [comment]
Looks like it's fixed now after #408, since these two PRs were merged around the same time and their versions came out correct. Technically there's still a race condition here, but the window is under a few seconds so it's unlikely to ever be a problem:

https://github.com/wakatime/wakatime-cli/releases/tag/v1.7.4-alpha.1
https://github.com/wakatime/wakatime-cli/releases/tag/v1.7.4-alpha.2
