### ISSUE TITLE
Seperate file for waketime.cfg/[settings] from [internal]

### ISSUE THREAD

**Issue by ryanerwin** [wakatime/wakatime-cli#535]
I like to use [dotbot](https://github.com/anishathalye/dotbot) to help keep a large fraction of my dotfiles consistent between machines.

Ideally I would like to symlink `Dotfiles/waketime.cfg` to -> `~/.wakatime.cfg`

The only problem is the `[internal]` section of the .cfg file is continually updated... So if I symlinked it directly, I would forever be committing new timestamps into version control.

```
[internal]
cli_version = v1.22.2
cli_version_last_modified = Mon, 06 Sep 2021 00:31:16 GMT¬
backoff_at                =
backoff_retries           = 0
```

Ideally it would be nice if the `[internal]` section was in it's own separate file.

Also, it would be ideal if you did something like:

`~/.config/wakatime/wakatime.cfg` and put the `wakatime.bdb`, `.data` `.db` and `.log` in there as well, so that our home folder can stay a little bit more orderly.

Of course it's possible to template the config file, which is tiny anyway, or just copy it over... 

Just would be nice if it worked a little bit more like all of the other programs that I use work.

**Comment by alanhamlett** [comment]
We'll add a config to the main `~/.wakatime.cfg` called `internal_config_location`. When that key is present, it will use the location provided for internal configs instead of modifying `~/.wakatime.cfg`.

**Comment by alanhamlett** [comment]
Would #464 will fix this, so you can include a cfg file containing your api key and other synced settings?

**Comment by nagromc** [comment]
I use a dotfiles manager ([chezmoi](https://github.com/twpayne/chezmoi)) as well, and this constant external update is pretty annoying.

I think the current `~/.wakatime.cfg` is mixing up two things:
- the user configuration. For instance:
  ```
  [settings]
  api_key = foobar
  ```
- the internal data needed by WakaTime (the `[internal]` section)

I think this should be split in two separate files without any additional configuration.

If you prefer not implement this out-of-the-box behavior, the solution suggested with the new `internal_config_location` option is the best because the solution suggested in #464 will force us to initialize the `~/.wakatime.cfg` manually before using WakaTime, which will defeat the whole purpose of having a dotfiles manager.

**Comment by alanhamlett** [comment]
We're now defaulting to `~/.wakatime-internal.cfg` for all internal configs, without needing any `internal_config_location` setting. You'll have to restart your editor to get the updated wakatime-cli with this change.
