### ISSUE TITLE
Changes for code readability

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/wakatime-cli#718]
1. Let's rename [this function](https://github.com/wakatime/wakatime-cli/blob/f64c00603b8457916e3568e12f8039d1ef7d5071/cmd/heartbeat/heartbeat.go#L75) because it's easily confused with `Sender.SendHeartbeats`, and vscode can't find implementations of `Sender.SendHeartbeats` because it's an interface. That means you have to search for `SendHeartbeats`, and the unrelated one shows up in the results.

2. How about removing `NewClient` and only use `NewClientWithoutAuth` then set the key on the request for fetching Goal and Today?

**Comment by gandarez** [comment]
1. vscode or other IDEs like Goland will properly find this implementation as you can see in the screenshoot below. IMO it's well written and describes exactly what the func is proposed to do. Any thoughts?
![Screen Shot 2022-05-04 at 17 47 39](https://user-images.githubusercontent.com/782854/166823769-c7fb9893-e1e4-4d2b-9c93-39c189f01c40.png)
2. I wouldn't remove `NewClient` just because `SendHeartbeat` doesn't need it. I'd keep it since Options pattern can benefit us for extensibility purposes. If new features come and authentication is needed `NewClient` will be ready for it.
